let movies = [
    {
        Id: 1,
        Name: ["Người Kiến Và Chiến Binh Ong: Thế Giới Lượng Tử", "Ant-Man and the Wasp: Quantumania (2023)"],
        Category: ["Phim Hành Động", "Phim Viễn Tưởng", "Phim Chiếu Rạp", "Phim Sắp Chiếu"],
        Year: 2023,
        Time: "125 Min",
        Director: "Peyton Reed",
        Actor: ["Paul Rudd", "Evangeline Lilly", "Michael Douglas"],
        Country: "Phim Âu Mỹ",
        Format: "Phim lẻ",
        Quality: ["HD", "Vietsub"],
    },
    {
        Id: 2,
        Name: "Avatar 2: Dòng Chảy Của Nước (2022)",
        Category: ["Phim Hành Động", "Phim Phiêu Lưu", "Phim Chiếu Rạp"],
        Year: 2022,
        Time: "120 Min",
        Director: "James Cameron",
        Actor: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Stephen Lang"],
        Country: "Phim Âu Mỹ",
        Format: "Phim lẻ",
        Quality: ["HD", "Vietsub"],
    },
    {
        Id: 3,
        Name: ["Shazam 2 Cơn Thịnh Nộ Của Các Vị Thần", "Shazam! Fury of the Gods (2023)"],
        Category: ["Phim Hành Động", "Phim Chiếu Rạp", "Phim Sắp Chiếu"],
        Year: 2023,
        Time: "130 Min",
        Director: "David F Sandberg",
        Actor: ["Zachary Levi", "Grace Caroline Currey", "Helen Mirren"],
        Country: "Phim Âu Mỹ",
        Format: "Phim lẻ",
        Quality: ["HD", "Vietsub"],
    },
    {
        Id: 4,
        Name: ["Sát thủ John Wick Phần 4", "John Wick: Chapter 4 (2023)"],
        Category: ["Phim Hành Động", "Phim Chiếu Rạp"],
        Year: 2023,
        Time: "169 Min",
        Director: "Chad Stahelski",
        Actor: ["Keanu Reeves", "Chân Tử Đan", "Scott Adkins", "Asia Kate Dillon", "Lance Reddick", "Ian McShane"],
        Country: "Phim Âu Mỹ",
        Format: "Phim lẻ",
        Quality: ["HD", "Vietsub"],
    },
    {
        Id: 5,
        Name: ["Anh Em Super Mario", "The Super Mario Bros. Movie (2023)"],
        Category: ["Phim Hoạt Hình", "Phim Phiêu Lưu", "Phim Chiếu Rạp", "Phim Sắp Chiếu"],
        Year: 2023,
        Time: "92 Min",
        Director: ["Aaron Horvath", "Michael Jelenic"],
        Actor: ["Chris Pratt", "Anya Taylor Joy", "Charlie Day", "Jack Black", "Keegan Michael Key", "Seth Rogen"],
        Country: "Phim Âu Mỹ",
        Format: "Phim lẻ",
        Quality: ["HD", "Vietsub"],
    },
];

export { movies };
